[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
dioxus-logger = { workspace = true }
{% if is_fullstack -%}
server = { workspace = true }
{%- endif %}