[template]

[hooks]
pre = ["init.rhai", "../common.rhai"]
post = ["conditional-files.rhai"]

[placeholders]
is_web = { prompt = "Do you want to build for Dioxus Web?", default = true, type = "bool" }
is_desktop = { prompt = "Do you want to build for Dioxus Desktop?", default = true, type = "bool" }
is_mobile = { prompt = "Do you want to build for Dioxus Mobile?", default = true, type = "bool" }

is_fullstack = { prompt = "Do you want to use Dioxus Fullstack?", default = true, type = "bool" }
is_router = { prompt = "Do you want to use the Dioxus Router?", default = true, type = "bool" }
is_tailwind = { prompt = "Do you want to use Tailwind CSS?", default = false, type = "bool" }
